_target_: model.net.FocalSTR
hidden_sizes: [192, 384, 768, 768]
embed_dim: 96
depths: [2, 2, 6, 2]
focal_levels: [2, 2, 2, 2]
focal_windows: [3, 3, 3, 3]
mlp_ratio: 4.0
hidden_dropout_prob: 0.0
drop_path_rate: 0.1
initializer_range: 0.02
layer_norm_eps: 1.0e-12
image_size: 128
patch_size: 4
num_channels: 3
threshold: 0.5
learning_rate: 1.0e-4
weight_decay: 0.0
warmup_pct: 0.3