_target_: model.FocalSTR.net.FocalSTR
# hidden_sizes: [128, 256, 512, 1024] # FocalNet Base
embed_dim: 128 # hidden_sizes will be embed_dim * (2 ** stage_no) starting from 0
depths: [2, 2, 18, 2]
focal_levels: [3, 3, 3, 3]
focal_windows: [3, 3, 3, 3]
mlp_ratio: 4.0
hidden_dropout_prob: 0.0
drop_path_rate: 0.1
initializer_range: 0.02
layer_norm_eps: 1.0e-12
image_size: 128
patch_size: 4
num_channels: 3
threshold: 0.5
learning_rate: 1.0e-4
weight_decay: 0.0
warmup_pct: 0.3