_target_: model.GrpNet.net.GroupNet
emb_path: /home/rohitn/IndianSTR/Img2Vec/GroupNet/embeddings/resnet_50_r256.pth
hidden_size: 768
num_hidden_layers: 12
num_attention_heads: 12
mlp_ratio: 4.0
hidden_dropout_prob: 0.0
attention_probs_dropout_prob: 0.0
initializer_range: 0.02
layer_norm_eps: 1.0e-12
image_size: 128
patch_size: 16 
num_channels: 3
qkv_bias: true
max_grps: 25
threshold:  0.5
learning_rate: 1.0e-4
weight_decay: 1.0e-4
warmup_pct: 0.3