_target_: model.GrpNet.net.HindiFocalGroupNet
emb_path: /home/rohitn/IndianSTR/Img2Vec/GroupNet/embeddings/new/focalnet_r256.pth
# hidden_sizes: [128, 256, 512, 1024]
embed_dim: 128
depths: [2, 2, 18, 2]
focal_levels: [2, 2, 2, 2]
focal_windows: [3, 3, 3, 3]
drop_path_rate: 0.1
mlp_ratio: 4.0 
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1 
initializer_range: 0.02
layer_norm_eps: 1.0e-12
image_size: 128 
patch_size: 4
num_channels: 3
qkv_bias: True
num_attention_heads: 16
max_grps: 25
threshold: 0.5
learning_rate: 1.0e-4
weight_decay: 1.0e-4
warmup_pct: 0.3