_target_: model.PosVisNet.net.ViTPosVisNet
hidden_size: 768
num_hidden_layers: 12
num_decoder_layers: 1
num_attention_heads: 12
mlp_ratio: 4.0
hidden_dropout_prob: 0.0
attention_probs_dropout_prob: 0.0
initializer_range: 0.02
layer_norm_eps: 1.0e-12
image_size: 128
patch_size: 8
num_channels: 3
qkv_bias: True
max_grps: 25
threshold: 0.5
learning_rate: 1.0e-4
weight_decay: 0.0
warmup_pct: 0.3