vyanjan: ['क', 'ख', 'ग', 'घ', 'ङ',
            'च', 'छ', 'ज', 'झ', 'ञ',
            'ट', 'ठ', 'ड', 'ढ', 'ण',
            'त', 'थ', 'द', 'ध', 'न',
            'प', 'फ', 'ब', 'भ', 'म',
            'य', 'र', 'ल', 'ळ', 'व', 'श',
            'ष', 'स', 'ह',
        ]
svar: ['अ', 'आ', 'इ', 'ई', 'उ', 
        'ऊ', 'ऋ', 'ॠ', 'ए', 'ऐ',
        'ओ', 'औ', 'ॲ', 'ऍ', 'ऑ'
      ]
matras: ['ा','ि','ी','ु','ू','ृ', 'े','ै', 'ो', 'ौ', 'ॅ', 'ॉ', 'ँ','ं', 'ः', '़']
chinh: ['ॐ', '₹', '।', '!', '$', ',', '.', '-', '%', '॥','ॽ']
ank: ['०','१','२','३','४','५','६' ,'७' ,'८' ,'९']
nukthas: ['क़', 'ख़', 'ग़', 'ज़', 'ड़', 'ढ़', 'ऱ'] # half-char cannot contain matras so added here
halanth: '्'