img_size: 128
log_dir: /global/D1/homes/rohitn/GrpNet_logs
name: vitstr_train_pretrain_w_glyphs
version: ${oc.env:SLURM_JOB_ID}
ckpt_path: null
half_character_classes: [ 'क', 'ख', 'ग', 'घ', 'ङ',
                            'च', 'छ', 'ज', 'झ', 'ञ',
                            'ट', 'ठ', 'ड', 'ढ', 'ण',
                            'त', 'थ', 'द', 'ध', 'न',
                            'प', 'फ', 'ब', 'भ', 'म',
                            'य', 'र', 'ल', 'ळ', 'व', 'श',
                            'ष', 'स', 'ह']
full_character_classes: ['अ', 'आ', 'इ', 'ई', 'उ', 
                        'ऊ', 'ऋ', 'ॠ', 'ए', 'ऐ',
                        'ओ', 'औ', 'ॲ', 'ऍ', 'ऑ',
                        'क', 'ख', 'ग', 'घ', 'ङ',
                        'च', 'छ', 'ज', 'झ', 'ञ',
                        'ट', 'ठ', 'ड', 'ढ', 'ण',
                        'त', 'थ', 'द', 'ध', 'न',
                        'प', 'फ', 'ब', 'भ', 'म',
                        'य', 'र', 'ल', 'ळ', 'व', 
                        'श', 'ष', 'स', 'ह',
                        'ॐ', '₹', '।', '!', '$', '₹', '%', '॥','ॽ', # characters that occur independently
                        '०','१','२','३','४','५','६' ,'७' ,'८' ,'९', # numerals
                        ]
diacritic_classes: ['ा','ि','ी','ु','ू','ृ', 'े','ै', 'ो', 'ौ', 'ॅ', 'ॉ', 'ँ','ं', 'ः', '़'] # ensure that halfer is not in this 
halfer: '्'

defaults: 
  - model: FocalSTR
  - _self_

model:
  half_character_classes: ${half_character_classes}
  full_character_classes: ${full_character_classes}
  diacritic_classes: ${diacritic_classes}
  halfer: ${halfer}

transforms:
  rotation: 90
  img_size: ${img_size}
  
datamodule:
  _target_: data.module.LMDBHindiDataModule
  train_dir: /home/rohitn/D1/HindiGlyphSynth/train1_lmdb
  val_dir: /home/rohitn/D1/HindiGlyphSynth/val_lmdb
  test_dir: null
  batch_size: 64 
  num_workers: 8
  drop_last: false
  half_character_classes: ${half_character_classes}
  full_character_classes: ${full_character_classes}
  diacritic_classes: ${diacritic_classes}
  halfer: ${halfer}

csv_logger:
  _target_: lightning.pytorch.loggers.CSVLogger
  save_dir: ${log_dir} # Do not put "/" at the end
  name: ${name}
  version: ${version} # using SLURM Job Id which is obtained in the train script
  # version: 82574/train2 # specify a sub-folder if continuing training

tensorboard_logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir:  ${log_dir}
  name: ${name}
  version: ${version}

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${log_dir}/${name}/${version}/checkpoints/      
  filename: "{epoch}-{val_loss:.2f}-{val_wrr2:.2f}"
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true

training:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu # options are cpu or gpu
  strategy: ddp # only use when gpu is available
  devices: 2
  max_epochs: 8
  # max_steps: 1000
  check_val_every_n_epoch: 1
  gradient_clip_val: 10
  precision: 32-true
  log_every_n_steps: 100
  num_nodes: 1

hydra:
  run:
    dir: ${log_dir}/${name}/${version}