dataset_name: IndicSTR12_${oc.env:SLURM_JOB_ID}
ckpt_root: /home/rohitn/D1/GrpNet_logs/vitstr_train/123309/checkpoints # do not keep a trailing "/"
ckpt_filename: epoch=7-val_loss_epoch=0.13-val_wrr_epoch=0.70.ckpt

model:
  _target_: model.net.FocalSTR.load_from_checkpoint
  # _target_: model.net.ViTSTR.load_from_checkpoint
  checkpoint_path: ${ckpt_root}/${ckpt_filename}
  
datamodule:
  _target_: data.module.LMDBHindiDataModule
  test_dir: /home/rohitn/D1/indicstr12/hindi_lmdb
  batch_size: 64 
  num_workers: 8
  drop_last: false

csv_logger:
  _target_: lightning.pytorch.loggers.CSVLogger
  save_dir: ${ckpt_root}
  name: test
  version: ${dataset_name}

tensorboard_logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: ${ckpt_root}
  name: test
  version: ${dataset_name} 

training:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu # options are cpu or gpu
  precision: 32-true
  log_every_n_steps: 100
  num_nodes: 1

hydra:
  run:
    dir: ${ckpt_root}/test/${dataset_name}