backbone: resnet
# ckpt_path: /home/rohitn/D1/logs/Img2Vec_resnet_50/2023-11-21/08-12-47/checkpoints/epoch=6-val_loss=0.99-val_acc=0.10.ckpt
ckpt_path: null
defaults:
  - model: resnet
  - _self_

model:
  img_size: 128
  version: 50

Img2Vec:
  _target_: model.Img2Vec.Img2Vec
  character_classes: ['क', 'क़', 'ख', 'ख़', 'ग़', 'ज़', 'ग', 'घ', 'ङ', 'ड़', 'च', 'छ', 'ज', 
    'झ', 'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ढ़', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 
    'प', 'फ', 'फ़', 'ब', 'भ', 'म', 'य', 'य़', 'र', 'ऱ', 'ल', 'ळ', 'ऴ', 'व', 
    'श', 'ष', 'स', 'ह', 'ऋ', 'ॠ', 'ॸ', 'ॹ', 'ॺ', 'ॻ', 'ॼ', 'ॾ', 'ॿ', 
    '०','१','२','३','४','५','६' ,'७' ,'८' ,'९', 
    'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऌ', 'ॡ', 'ऋ', 'ॠ', 'ए', 'ऐ', 'ऎ', 'ऒ', 
    'ओ', 'औ', 'ॲ', 'ऍ', 'ऑ', 'ऄ', 'ॳ', 'ॴ', 'ॵ', 'ॶ', 'ॷ',
    '।', '!', '$', '₹', '%', '॥','ॽ',
    'ऽ', 'ॐ']

  diacritic_classes: ['ा','ि','ी','ु','ू','ृ','ॄ', 'ॢ', 'ॣ', 'े','ै', 'ॆ', 'ॊ', 'ो', 'ौ', 'ॏ', 'ऺ', 
    '़', 'ॅ', 'ॉ', 'ँ','ं','ः', 'ऻ', 'ॎ', '॑', '॒', '॓', '॔', 'ॕ', 'ॖ', 'ॗ', '॰', 'ॱ'] # ensure that halfer is not in this
    
  half_character_classes: ['क', 'क़', 'ख', 'ख़', 'ग़', 'ज़', 'ग', 'घ', 'ङ', 'ड़', 'च', 'छ', 'ज', 
    'झ', 'ञ', 'ट', 'ठ', 'ड', 'ढ', 'ढ़', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'ऩ', 
    'प', 'फ', 'फ़', 'ब', 'भ', 'म', 'य', 'य़', 'र', 'ऱ', 'ल', 'ळ', 'ऴ', 'व', 
    'श', 'ष', 'स', 'ह', 'ऋ', 'ॠ', 'ॸ', 'ॹ', 'ॺ', 'ॻ', 'ॼ', 'ॾ', 'ॿ']
  optimizer:
    _partial_: true
    _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 0.01
  threshold: 0.5
  backbone: ${model}
  rep_dim: 2048
  activation:
    _target_: torch.nn.ReLU
    
transforms:
  rotation: 60
  img_size: ${model.img_size}
  
datamodule:
  _target_: data.module.DevanagariDataModule
  charset: ${Img2Vec.character_classes}
  diacritics: ${Img2Vec.diacritic_classes}
  halfer: '्'
  half_charset: ${Img2Vec.half_character_classes}
  train_img_dir: /global/D1/homes/rohitn/glyph_train1
  train_gt: /global/D1/homes/rohitn/glyph_train1/gt.txt
  val_img_dir: /global/D1/homes/rohitn/glyph_val
  val_gt: /global/D1/homes/rohitn/glyph_val/gt.txt
  test_img_dir: null
  test_gt: null
  delimiter: "\t"
  batch_size: 256
  num_workers: 4

csv_logger:
  _target_: lightning.pytorch.loggers.CSVLogger
  save_dir: /global/D1/homes/rohitn/logs # Do not put "/" at the end
  name: Img2Vec_${backbone}_${model.version}_v4
  version: ${now:%Y-%m-%d}/${now:%H-%M-%S}
  # version: 2023-11-21/08-12-47/matra_train # specify a sub-folder if finetuning

tensorboard_logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir:  ${csv_logger.save_dir}
  name: ${csv_logger.name}
  version: ${csv_logger.version}

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${csv_logger.save_dir}/${csv_logger.name}/${csv_logger.version}/checkpoints/      
  filename: "{epoch}-{val_loss:.2f}-{val_acc:.2f}"
  monitor: val_acc
  mode: max
  save_top_k: 3
  save_last: true
  
early_stopping:
  _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
  monitor: train_loss_epoch
  mode: min
  min_delta: 0.1
  patience: 1
  verbose: true
  check_finite: true

training:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu # options are cpu or gpu
  strategy: auto # only use when gpu is available
  devices: 1
  max_epochs: 10
  check_val_every_n_epoch: 1
  gradient_clip_val: 10
  precision: 32-true
  log_every_n_steps: 5

hydra:
  run:
    dir: ${csv_logger.save_dir}/${csv_logger.name}/${csv_logger.version}
