backbone: resnet_50
img_size: 128

defaults: 
  - model: resnet
  - _self_

model: # for resnet
  img_size: ${img_size}

# model: # for focalnet
#   config:
#     image_size: ${img_size}

Img2Vec:
  _target_: model.Img2Vec.Img2Vec
  character_classes: ['अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ऋ', 'ॠ', 'ए', 'ऐ',
                      'ओ', 'औ', 'ॲ', 'ऍ', 'ऑ',
                      'क', 'ख', 'ग', 'घ', 'ङ',
                      'च', 'छ', 'ज', 'झ', 'ञ',
                      'ट', 'ठ', 'ड', 'ढ', 'ण',
                      'त', 'थ', 'द', 'ध', 'न',
                      'प', 'फ', 'ब', 'भ', 'म',
                      'य', 'र', 'ल', 'ळ', 'व', 'श',
                      'ष', 'स', 'ह',
                      #'क़', 'ख़', 'ग़', 'ज़', 'झ़', 'ड़', 'ढ़', 'फ़' # these will be handled by the matra '़'
                      # For real text, each of these will be converted to vyanjan + matra
                      'ॐ', '₹', '।', '!', '$', '₹', '%', '॥','ॽ', # characters that occur independently
                      '०','१','२','३','४','५','६' ,'७' ,'८' ,'९',
                      ]

  diacritic_classes: ['ा','ि','ी','ु','ू','ृ', 'े','ै', 'ो', 'ौ', 'ॅ', 'ॉ', 'ँ','ं', 'ः', '़'] # ensure that halfer is not in this
    
  half_character_classes: [ 'क', 'ख', 'ग', 'घ', 'ङ',
                            'च', 'छ', 'ज', 'झ', 'ञ',
                            'ट', 'ठ', 'ड', 'ढ', 'ण',
                            'त', 'थ', 'द', 'ध', 'न',
                            'प', 'फ', 'ब', 'भ', 'म',
                            'य', 'र', 'ल', 'ळ', 'व', 'श',
                            'ष', 'स', 'ह']
  optimizer:
    _partial_: true
    _target_: torch.optim.AdamW
  threshold: 0.5
  backbone: ${model}
  activation:
    _target_: torch.nn.GELU
  
search_space:
  lr:
    min: 1.0e-8
    max: 1.0e-1
  weight_decay:
    min: 1.0e-8
    max: 1.0e-1
  rep_dim: [256, 512, 768, 1024, 1280, 1536, 1792, 2048]
  swa_lrs:
    min: 1.0e-8
    max: 1.0e-1
    

tune_config:
  metric: val_acc
  mode: max
  num_samples: 50
  cpu_per_trial: 8
  gpu_per_trial: 1 

scheduler:
  _target_: ray.tune.schedulers.ASHAScheduler
  max_t: 50
  grace_period: 1
  reduction_factor: 3

run_config:
  _target_: ray.train.RunConfig
  checkpoint_config:
    _target_: ray.train.CheckpointConfig
    num_to_keep: 2
    checkpoint_score_attribute: val_acc
    checkpoint_score_order: max

transforms:
  rotation: 90
  img_size: ${img_size}
  
datamodule:
  _target_: data.module.LMDBDevanagariDataModule
  charset: ${Img2Vec.character_classes}
  diacritics: ${Img2Vec.diacritic_classes}
  halfer: '्'
  half_charset: ${Img2Vec.half_character_classes}
  train_dir: /home/rohitn/D1/HindiGlyphSynth/train1_lmdb
  val_dir: /home/rohitn/D1/HindiGlyphSynth/val_lmdb
  false_sample_dir: /home/rohitn/D1/HindiGlyphSynth/coco
  false_train_wt: 3
  false_val_wt: 1
  test_dir: null
  delimiter: "\t"
  batch_size: 32
  num_workers: 8

tensorboard_logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir: /home/rohitn/D1/Hindi_embed_logs/tune
  name: Img2Vec_${backbone}
  version: ${oc.env:SLURM_JOB_ID}

training:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu # options are cpu or gpu
  strategy: auto # only use when gpu is available
  devices: auto
  check_val_every_n_epoch: 1
  gradient_clip_val: 10
  precision: 32-true
  num_nodes: 1

hydra:
  run:
    dir: ${tensorboard_logger.save_dir}/${tensorboard_logger.name}/${tensorboard_logger.version}
