backbone: resnet
# ckpt_path: /home/rohitn/D1/Hindi_embed_logs/Img2Vec_resnet_50_r512/82574/train1/checkpoints/epoch=12-val_loss=0.24-val_acc=0.84.ckpt
ckpt_path: null
img_size: 128

defaults: 
  - model: resnet
  - _self_

model: # for resnet
  img_size: ${img_size}

# model: # for focalnet
#   config:
#     image_size: ${img_size}

Img2Vec:
  _target_: model.Img2Vec.Img2Vec
  half_character_classes: [ 'क', 'ख', 'ग', 'घ', 'ङ',
                            'च', 'छ', 'ज', 'झ', 'ञ',
                            'ट', 'ठ', 'ड', 'ढ', 'ण',
                            'त', 'थ', 'द', 'ध', 'न',
                            'प', 'फ', 'ब', 'भ', 'म',
                            'य', 'र', 'ल', 'ळ', 'व', 'श',
                            'ष', 'स', 'ह']
  character_classes: ['अ', 'आ', 'इ', 'ई', 'उ', 
                      'ऊ', 'ऋ', 'ॠ', 'ए', 'ऐ',
                      'ओ', 'औ', 'ॲ', 'ऍ', 'ऑ',
                      'क', 'ख', 'ग', 'घ', 'ङ',
                      'च', 'छ', 'ज', 'झ', 'ञ',
                      'ट', 'ठ', 'ड', 'ढ', 'ण',
                      'त', 'थ', 'द', 'ध', 'न',
                      'प', 'फ', 'ब', 'भ', 'म',
                      'य', 'र', 'ल', 'ळ', 'व', 
                      'श', 'ष', 'स', 'ह',
                      'ॐ', '₹', '।', '!', '$', ',', '.', '-', '%', '॥','ॽ', # characters that occur independently
                      '०','१','२','३','४','५','६' ,'७' ,'८' ,'९', # numerals
                      ]

  diacritic_classes: ['ा','ि','ी','ु','ू','ृ', 'े','ै', 'ो', 'ौ', 'ॅ', 'ॉ', 'ँ','ं', 'ः', '़'] # ensure that halfer is not in this

  optimizer:
    _partial_: true
    _target_: torch.optim.AdamW
  lr: 1.0e-4
  weight_decay: 0.0
  threshold: 0.5
  backbone: ${model}
  rep_dim: 256
  activation:
    _target_: torch.nn.GELU
    
transforms:
  rotation: 90
  img_size: ${img_size}
  
# datamodule:
#   _target_: data.module.DevanagariDataModule
#   charset: ${Img2Vec.character_classes}
#   diacritics: ${Img2Vec.diacritic_classes}
#   halfer: '्'
#   half_charset: ${Img2Vec.half_character_classes}
#   train_img_dir: /home/rohitn/D1/HindiGlyphSynth/glyph_train1
#   train_gt: /home/rohitn/D1/HindiGlyphSynth/glyph_train1/gt.txt
#   val_img_dir: /home/rohitn/D1/HindiGlyphSynth/glyph_val
#   val_gt: /home/rohitn/D1/HindiGlyphSynth/glyph_val/gt.txt
#   false_sample_dir: /home/rohitn/D1/COCO
#   false_sample_gt: /home/rohitn/D1/COCO/image_names.txt
#   false_train_wt: 3
#   false_val_wt: 1
#   test_img_dir: null
#   test_gt: null
#   delimiter: "\t"
#   batch_size: 32
#   num_workers: 8

datamodule:
  _target_: data.module.LMDBDevanagariDataModule
  charset: ${Img2Vec.character_classes}
  diacritics: ${Img2Vec.diacritic_classes}
  halfer: '्'
  half_charset: ${Img2Vec.half_character_classes}
  train_dir: /work/rohitn/hindi_glyph_train_lmdb
  val_dir: /work/rohitn/hindi_glyph_val_lmdb
  false_sample_dir: /work/rohitn/coco
  false_train_wt: 2
  false_val_wt: 0
  test_dir: null
  delimiter: "\t"
  batch_size: 64
  num_workers: 8

csv_logger:
  _target_: lightning.pytorch.loggers.CSVLogger
  save_dir: /global/D1/homes/rohitn/Hindi_embed_logs # Do not put "/" at the end
  name: Img2Vec_${backbone}_r${Img2Vec.rep_dim}
  version: ${oc.env:SLURM_JOB_ID} # using SLURM Job Id which is obtained in the train script
  # version: 82574/train2 # specify a sub-folder if continuing training

tensorboard_logger:
  _target_: lightning.pytorch.loggers.TensorBoardLogger
  save_dir:  ${csv_logger.save_dir}
  name: ${csv_logger.name}
  version: ${csv_logger.version}

model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${csv_logger.save_dir}/${csv_logger.name}/${csv_logger.version}/checkpoints/      
  filename: "{epoch}-{val_loss:.2f}-{val_acc:.2f}"
  monitor: val_acc
  mode: max
  save_top_k: 3
  save_last: true
  
early_stopping:
  _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
  monitor: val_loss
  mode: min
  min_delta: 0.01
  patience: 1
  verbose: true
  check_finite: true

training:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu # options are cpu or gpu
  strategy: ddp # only use when gpu is available
  devices: 2
  max_epochs: 10
  check_val_every_n_epoch: 1
  gradient_clip_val: 10
  precision: 32-true
  log_every_n_steps: 100
  num_nodes: 1

hydra:
  run:
    dir: ${csv_logger.save_dir}/${csv_logger.name}/${csv_logger.version}
